#include "UEGT2LogChannels.h"

DEFINE_LOG_CATEGORY(LogUEGT2);
DEFINE_LOG_CATEGORY(LogUEGT2Player);
DEFINE_LOG_CATEGORY(LogUEGT2Interaction);
DEFINE_LOG_CATEGORY(LogUEGT2Settings);
DEFINE_LOG_CATEGORY(LogUEGT2UI);
DEFINE_LOG_CATEGORY(LogUEGT2World);
DEFINE_LOG_CATEGORY(LogUEGT2Diag);
